import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import Footer from '../components/Footer';
import NavBar from '../components/Menu';
import { Col, Row } from 'react-bootstrap';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
      <title>Leaf DAO - Home</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar />

        <Row className='container-home'>
        <Col className='homeBox p-5 m-2'>
          <p>
            sdfsee
          </p>
          <p>
            sadgasdg
          </p>
        </Col>
        <Col className='homeBox p-5 m-2'>
          <p>
            sdfsee
          </p>
          <p>
            sadgasdg
          </p>
        </Col>
        <Col className='homeBox p-5 m-2'>
          <p>
            sdfsee
          </p>
          <p>
            sadgasdg
          </p>
        </Col>
        </Row>
      </main>

      <Footer/>
    </div>
  );
};

export default Home;
