/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as compatibility from "./compatibility";
export type { compatibility };
import type * as extensions from "./extensions";
export type { extensions };
export type { GovernorUpgradeable } from "./GovernorUpgradeable";
export type { IGovernorUpgradeable } from "./IGovernorUpgradeable";
